name: Test module

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish images"]
    types: [completed]

jobs:
  module:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == '' }}
    uses: NethServer/ns8-github-actions/.github/workflows/module-info.yml@main
  run_tests:
    needs: module
    uses: NethServer/ns8-github-actions/.github/workflows/test-on-ubuntu-runner.yml@main
    with:
      coremodules: "ghcr.io/${{needs.module.outputs.owner}}/${{needs.module.outputs.name}}:${{needs.module.outputs.tag}}"
      repo_ref: ${{needs.module.outputs.sha}}
  run_tests_on_do:
    needs: module
    uses: NethServer/ns8-github-actions/.github/workflows/test-on-digitalocean-infra.yml@do_infra
    with:
      coremodules: "ghcr.io/${{needs.module.outputs.owner}}/${{needs.module.outputs.name}}:${{needs.module.outputs.tag}}"
      repo_ref: ${{needs.module.outputs.sha}}
    secrets:
      do_token: ${{ secrets.do_token }}
